apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnTaskDefinition
metadata:
  name: check-infrastructure-state
spec:
  function:
    httpRef:
      url: https://raw.githubusercontent.com/thschue/environment-readiness-service/main/keptn/get_state.ts
    parameters:
      map:
        url: http://environment-readiness-service.default.svc.cluster.local:8080